# Generated by Django 3.0.3 on 2020-02-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_member', models.CharField(default='', max_length=20)),
                ('first_name', models.CharField(default='', max_length=150)),
                ('last_name', models.CharField(default='', max_length=150)),
                ('birth_date', models.DateField()),
                ('place_birth', models.CharField(default='', max_length=150)),
                ('sex', models.CharField(choices=[('M', 'Serigne'), ('F', 'Soxna')], default='M', max_length=1)),
                ('mariage_status', models.CharField(choices=[('S', 'Célibataire'), ('C', 'Marié(e)'), ('D', 'Divorcé(e)'), ('W', 'Veuf(ve)')], default='S', max_length=1)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('home_addr', models.CharField(default='', max_length=150)),
                ('current_addr', models.CharField(default='', max_length=150)),
                ('identity_photo', models.ImageField(upload_to='')),
                ('phone_number1', models.CharField(default='', max_length=14)),
                ('phone_number2', models.CharField(default='', max_length=14)),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
