# Generated by Django 3.0.3 on 2020-02-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='sex',
            field=models.CharField(choices=[('M', 'Serigne'), ('W', 'Soxna')], default='M', max_length=1),
        ),
    ]
