# Generated by Django 3.0.3 on 2020-02-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20200216_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='code_member',
            field=models.CharField(default='DFF120190001', max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='identity_photo',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
