# Generated by Django 3.0.3 on 2020-02-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20200216_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='identity_photo',
            field=models.ImageField(upload_to=None, verbose_name='identity'),
        ),
        migrations.AlterField(
            model_name='member',
            name='register_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
