# Generated by Django 3.0.3 on 2020-02-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_auto_20200216_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='current_addr',
            field=models.CharField(default='Bambey', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(default='', max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='home_addr',
            field=models.CharField(default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='identity_photo',
            field=models.ImageField(null=True, upload_to=None, verbose_name='identity'),
        ),
        migrations.AlterField(
            model_name='member',
            name='mariage_status',
            field=models.CharField(choices=[('S', 'Célibataire'), ('C', 'Marié(e)'), ('D', 'Divorcé(e)'), ('W', 'Veuf(ve)')], default='S', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_number1',
            field=models.CharField(default='', max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_number2',
            field=models.CharField(default='', max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='place_birth',
            field=models.CharField(default='', max_length=150, null=True),
        ),
    ]
