# Generated by Django 3.0.3 on 2020-02-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_auto_20200216_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone_number1',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_number2',
            field=models.IntegerField(blank=True),
        ),
    ]
