# Generated by Django 3.0.3 on 2020-02-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0010_auto_20200217_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='register_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
