# Generated by Django 3.0.3 on 2020-02-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0013_auto_20200217_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone_number1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_number2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
