# Generated by Django 3.0.3 on 2020-02-17 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cell', '0001_initial'),
        ('member', '0014_auto_20200217_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='cell_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cell.Cell'),
        ),
    ]
