# Generated by Django 3.0.3 on 2020-02-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0015_member_cell_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone_number1',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_number2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
