# Generated by Django 3.0.3 on 2020-02-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_label', models.CharField(max_length=40)),
                ('cell_addr', models.CharField(max_length=40)),
                ('cell_link_map', models.URLField(max_length=255)),
            ],
        ),
    ]
